# =============================================================================
# PEMF Gateway - Mosquitto MQTT Broker Yapilandirmasi
# =============================================================================

# listener 1883 0.0.0.0 is used to accept connections from all interfaces
listener 1883 0.0.0.0

allow_anonymous true

# We disable persistence and file logging to avoid path permission and missing folder errors
# when running as a portable executable extracted from PyInstaller.
persistence false

max_queued_messages 10000
max_queued_bytes 0
max_inflight_messages 40
max_connections 100
max_keepalive 120
retain_available true

# Log into console/stderr instead of stdout, avoiding Windows stdout pipe crashes
# log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
